### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lulzkid** [AlaBouali/cfkiller#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\cfkiller.py", line 339, in <module>
    cfkiller(u,threads=th)
  File "C:\Users\Administrator\Desktop\cfkiller.py", line 315, in cfkiller
    atcf().start()
  File "C:\Python27\lib\threading.py", line 675, in __init__
    self.__name = str(name or _newname())
  File "C:\Python27\lib\threading.py", line 621, in _newname
    return template % _counter()
KeyboardInterrupt
I trying in Python 2.7.14

**Comment by AlaBouali** [comment]
try in python 2.7.15 and check it again plz :)

**Comment by lulzkid** [comment]
work on uam, I thought on captcha :v, nice code <3
