### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Udyz** [AlaBouali/cfkiller#3]
Exception in thread Thread-401:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cfkiller.py", line 5603, in run
    a=random.choice(ual)
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range

**Comment by Udyz** [comment]
i have install cfscrape,requests, nodejs but i attack a web not cloudflare

**Comment by lulzkid** [comment]
@Udyz only attack on web protection by cloudflare

**Comment by AlaBouali** [comment]
First of all, thank your for trying my tool. Second, this tool was only designed to bypass cloudflare's protections, if you use it on non cloudflare site, it won't work!!
